services:
  couchdb:
    image: couchdb:3.5
    environment:
      COUCHDB_USER: skyr
      COUCHDB_PASSWORD: password123
    ports:
      - 5984:5984

  redis:
    image: redis:8.4
    ports:
      - 6379:6379
