version = 2

[plugins."io.containerd.grpc.v1.cri"]
  sandbox_image = "registry.k8s.io/pause:3.9"

  [plugins."io.containerd.grpc.v1.cri".containerd]
    snapshotter = "native"
    default_runtime_name = "crun"

    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.crun]
      runtime_type = "io.containerd.runc.v2"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.crun.options]
        BinaryName = "/usr/bin/crun"
        SystemdCgroup = false

  [plugins."io.containerd.grpc.v1.cri".registry]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      # OCI registry is on the host, reachable via QEMU gateway
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."10.0.2.2:5000"]
        endpoint = ["http://10.0.2.2:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."10.0.2.2:5000".tls]
        insecure_skip_verify = true
