// ============================================================================
//  Chapter 4 — The type language
// ============================================================================

#import "preamble.typ": *

= Types

This chapter fixes the language of _types_ that is used throughout the
static semantics. The type language is slightly richer than the surface
type syntax of Chapter 3: it includes μ-types for recursion, type
variables for inference, and a distinguished bottom type `Never`. All of
these arise internally during type checking even when they do not
appear in source programs.

== The type language

We take the type language to be generated by the following grammar,
where $id$ ranges over an enumerable set of type-variable identifiers:

#align(center)[
    #table(
        columns: (auto, 1fr),
        stroke: none,
        inset: (x: 6pt, y: 2pt),
        align: (right + top, left + top),
        [$A, B$], [$::=$ #raw("Any") | #raw("Int") | #raw("Float") | #raw("Bool") | #raw("Str") | #raw("Path")],
        [],    [$|$ #raw("Never")],
        [],    [$|$ $A ?$ #h(0.6em) _(optional)_],
        [],    [$|$ $[ A ]$ #h(0.6em) _(list)_],
        [],    [$|$ $hash {A_1 colon A_2}$ #h(0.6em) _(dict)_],
        [],    [$|$ ${overline(f colon A)}$ #h(0.6em) _(record)_],
        [],    [$|$ $forall overline(alpha asgn A) . ( overline(A) ) arrow B$ #h(0.6em) _(function)_],
        [],    [$|$ $alpha^id$ #h(0.6em) _(type variable)_],
        [],    [$|$ $mu alpha . A$ #h(0.6em) _(iso-recursive type)_],
        [],    [$|$ $E$ #h(0.6em) _(exception)_],
    )
]

We write #raw("Any") and #raw("Never") for the top and bottom types,
respectively; $A ?$ as sugar for a one-constructor nullable; and
$E$ for a _nominal_ exception type identified by a unique 64-bit
identifier generated at its introduction site. Two occurrences of
#kw("exception") in source code introduce distinct $E$s.

Record types are modelled as finite maps $f mapsto A$ from field names
to types, not as ordered tuples. The formal system is therefore
commutative in record field order. The implementation stores fields in
an ordered map keyed by name, which is observable only at the
string-formatting level (e.g. in error messages).

The function type form $forall overline(alpha asgn A) . ( overline(A) ) arrow B$
is a _polymorphic_ type quantifying over type variables $alpha_i$, each
with a declared upper bound $A_i$ (defaulting to #raw("Any")). A
_monomorphic_ function type is a polymorphic function type with an
empty binder list and is written simply $(overline(A)) arrow B$.

== Type identities

Each type carries, in addition to its shape, an _origin identifier_
$id in bb(N)$. Origin identifiers are fresh by default and are
equipped with an explicit _sharing_ operation $dot chevron.l id chevron.r$
that attaches a particular identifier to a type. Origin identifiers
are invisible to type equality — two types are equal iff their shapes
are equal — but they are load-bearing for the propositional refinement
system of Chapter 6, which addresses types _by origin_ rather than
structurally.

#remark[
    Thinking of types as having both a structure and an origin, a
    useful analogue is that of an SSA value in an optimising compiler:
    two SSA values may have equal types and equal dataflow, yet remain
    distinct for purposes such as liveness analysis. Origin identifiers
    play exactly this role for propositional refinement.
]

== μ-types and unfolding

We admit iso-recursive types $mu alpha . A$ with a single level of
iso-recursion per binder. The reference implementation encodes these as
`TypeKind::IsoRec(id, body)` with a single structural step relation:

$
mu alpha . A ≡ A[mu alpha . A slash alpha]
$

i.e. _unfolding_ is a structural equivalence that replaces the bound
variable by the whole μ-type wherever it occurs. Unfolding is applied
lazily: the subtyping judgment of Chapter 5 unfolds either side exactly
once whenever one of them is an iso-recursive type.

A μ-type whose body does not mention the bound variable is semantically
equivalent to that body. The reference implementation's `unfold`
operation detects and simplifies this case; the formal system regards
any $mu alpha . A$ with $alpha in.not $ #raw("ftv")$(A)$ as equal to
$A$.

== Variables, substitution, and free variables

A type variable $alpha^id$ is a _placeholder_ awaiting solution. Type
variables arise in three contexts: as _declared_ generics introduced by
#kw("fn") and #kw("type"), as _fresh_ unknowns introduced during
inference, and as the recursion binder of a μ-type.

_Substitution_, written $A [B slash alpha]$, replaces every
free occurrence of $alpha$ in $A$ with $B$. It is defined structurally
and is the identity on all base types, on variables with a different
identifier, and on the bound variable of a μ-binder naming $alpha$. We
extend substitution to _simultaneous_ substitution over a list of
bindings in the usual way.

The set #raw("ftv")$(A)$ of _free type variables_ of $A$ is defined by
structural recursion, with #raw("ftv")$(alpha^id) = { alpha^id }$ and
#raw("ftv")$(mu alpha . A) = $ #raw("ftv")$(A) without { alpha }$.

== The assignability relation at a glance

A recurring convention in this specification is that the relation
written $B subtype A$ should be read as "a value of type $B$ is
assignable to a target of type $A$". This is the usual subtyping
relation of the theory of records and functions, extended with two
convenient rules:

- $B subtype$ #raw("Any") for every $B$, and
- #raw("Never") $subtype A$ for every $A$.

Chapter 5 develops the relation in full.

== Primitive types

The six primitive types have the following intended interpretations:

#align(center)[
    #table(
        columns: 2,
        stroke: 0.4pt,
        inset: (x: 6pt, y: 4pt),
        [#raw("Int")], [Mathematical integers representable as 64-bit two's-complement signed integers; overflow is an evaluation error.],
        [#raw("Float")], [IEEE-754 binary64 values except for NaN; the absence of NaN is enforced at the value level by the `NotNan<f64>` representation.],
        [#raw("Bool")], [The two-element set ${top, bot}$.],
        [#raw("Str")], [Finite sequences of Unicode scalar values.],
        [#raw("Path")], [Repository-root-relative file-system paths, represented as #raw("Str") after resolution.],
        [#raw("Any")], [The unit of subtyping — the top type.],
    )
]

The distinction between #raw("Any") and a record type with no fields
is notable: ${}$ is a record with no fields and rejects every
non-record value, whereas #raw("Any") accepts every value. A program
that genuinely does not care about a value's shape should be typed
with #raw("Any"), not with the empty record.

== Exception types

The type of an exception value is #raw("Exception"), parameterised by a
unique 64-bit identifier generated at the introduction site of the
#kw("exception") keyword. Two calls to #kw("exception") yield
exception types with distinct identifiers, regardless of whether they
are structurally identical. The payload type, if any, is carried
separately by the static binding of the exception's name; see
Section 7.15.
