// ============================================================================
//  Chapter 6 — Propositional type refinement
// ============================================================================

#import "preamble.typ": *

= Propositional Type Refinement

SCL's most distinctive static-semantic feature is _propositional type
refinement_. Rather than narrowing types directly along branches of a
conditional, the type checker emits and propagates _propositions_ about
values — atomic claims that a particular value is true or that a type
of a particular origin can be replaced by a sharper type — and then
consults a small forward-chaining proof engine at every use site to
decide which refinements actually apply.

This indirection is deliberate: it permits an uncoordinated collection
of rules, each emitting its own propositions, to combine cleanly
through logical implication, and it allows refinement to cross
abstraction boundaries that a direct narrowing discipline would block.

== The language of propositions

Propositions are generated by the following grammar:

#align(center)[
    #table(
        columns: (auto, 1fr),
        stroke: none,
        inset: (x: 6pt, y: 2pt),
        align: (right + top, left + top),
        [$p$], [$::=$ $"IsTrue"(id)$ #h(0.6em) _(atomic truth)_],
        [],    [$|$ $"RefinesTo"(id, A)$ #h(0.6em) _(atomic refinement)_],
        [],    [$|$ $not p$],
        [],    [$|$ $p_1 implies p_2$],
    )
]

The atom $"IsTrue"(id)$ asserts that the value bearing origin identifier
$id$ evaluates to Boolean _true_. The atom $"RefinesTo"(id, A)$
asserts that the type with origin identifier $id$ may be replaced by
$A$ at every use site that consults the refinement map. Negation and
implication are the usual classical connectives; conjunction and
disjunction are not atomic but are freely expressible by implication
chains and negation, and the reference implementation does not admit
them as primitive.

A _proposition set_ $Pi$ is a finite set of propositions. A _proven
set_ $cal(P)$ is a proposition set augmented with an efficient index of
its implications and a map

$ cal(R) : "id" arrow A $

recording atomic refinements $"RefinesTo"(id, A)$ that have been
proven. We write $cal(P) ts p$ for the proof-theoretic derivability of
$p$ from $cal(P)$; concretely, this is decided by the forward-chaining
algorithm of Section 6.3.

== Equality of propositions

Two propositions are equal iff their shapes and _origin identifiers_
are equal. In particular, two atomic refinements $"RefinesTo"(id, A)$
and $"RefinesTo"(id, A')$ are considered equal iff $A$ and $A'$ have
_the same origin identifier_, not merely the same structure. This
design reflects the pragmatic observation that origin-level sharing
is a stronger indicator of semantic sameness than structural equality,
which under μ-types and type variables can be non-obvious to compute.

== The forward-chaining engine

The proven set $cal(P)$ supports a single operation, _extend_, which
adds a collection of new propositions and returns an updated proven set
with all derived consequences:

$ cal(P) union.plus Pi : cal(P)' $

The algorithm proceeds one proposition at a time. For each new
proposition $p$:

+ If $p$ is atomic:
    - If $p$ is already in $cal(P)$, return unchanged.
    - If $p = "RefinesTo"(id, A)$, record $cal(R)(id) := A$.
    - Add $p$ to the proven set.
    - For every implication $p implies q$ indexed by antecedent $p$,
      recursively extend by $q$.
+ If $p = p_1 implies p_2$:
    - If $cal(P) ts p_1$, recursively extend by $p_2$.
    - Otherwise, index $p$ under its antecedent $p_1$ so that if $p_1$
      is ever proven later, $p_2$ will be extended transitively.
+ If $p = not p'$, treat as atomic (i.e. add to the proven set as a
  distinct entry).

The algorithm terminates because every proposition is extended at most
once (entries are memoised by equality), and forward-chaining through
indexed implications consumes each index entry exactly once. Soundness
is immediate: every step is modus ponens.

#remark[
    The engine is intentionally _incomplete_ for propositional logic:
    it cannot perform proof by contradiction or case analysis, and it
    does not handle disjunctions. In practice this is a feature — the
    static semantics becomes predictable and performs no search. The
    completeness the engine does have — transitive forward-chaining
    over atomic antecedents — suffices for every refinement pattern
    that arises naturally from Boolean tests over optional values.
]

== The refinement map

The map $cal(R)$ derived from the proven set is applied at every use
site that consults refinement: variable lookup, property access,
indexed access, and the result of any expression whose type is to be
reported to the programmer. Applying $cal(R)$ to a type $A$ means
walking $A$ structurally, and, at every node whose origin identifier is
mapped by $cal(R)$, substituting the mapped replacement in its place.

Formally, $"refine"_cal(R) : "Type" arrow "Type"$ is defined as the
fixpoint of

$
"refine"_cal(R) (A) = cases(
    "refine"_cal(R) (cal(R)(id))          &"if" id in "dom"(cal(R)) and A "has origin" id,
    "refine"_cal(R) (A[ overline("refine"_cal(R) (A_i)) slash overline(A_i)]) quad &"otherwise",
)
$

where the $overline(A_i)$ range over the subterms of $A$. The
fixpoint is immediate when $cal(R)$ is acyclic, which the reference
implementation guarantees by construction; if ever $cal(R)$ were
permitted to be cyclic, the fixpoint would be computed by Kleene
iteration up to the length of the longest simple chain.

== Emission sites

Propositions are _emitted_ by the typing rules of Chapter 7; this
section catalogues the sites.

=== Nil-comparison

An expression $e_1 plus.o e_2$ with $plus.o in { #raw("=="), #raw("!=") }$
where one operand is syntactically #kw("nil") and the other is of
optional type $A?$ with origin $id$ emits:

#align(center)[
    #table(
        columns: 2,
        stroke: 0.4pt,
        inset: (x: 6pt, y: 4pt),
        [$e == #kw("nil")$], [$not "IsTrue"("id"("result"))$ $implies$ $"RefinesTo"(id, A)$, $ "IsTrue"("id"("result")) implies "RefinesTo"(id, #raw("Never")?)$],
        [$e != #kw("nil")$], [$"IsTrue"("id"("result")) implies "RefinesTo"(id, A)$, $not "IsTrue"("id"("result")) implies "RefinesTo"(id, #raw("Never")?)$],
    )
]

i.e. the truth value of the comparison determines which of the two
possible shapes of $e$ is in play, and the type of $e$ may be
refined accordingly.

=== Boolean-literal comparison

An expression $e_1 plus.o e_2$ with $plus.o in { #raw("=="), #raw("!=") }$
where one operand is syntactically the literal #kw("true") or
#kw("false") and the other is $e$ with origin $id$ emits implications
linking the truth value of the comparison's result (of origin
$id_r$) to the truth value of $e$:

#align(center)[
    #table(
        columns: 2,
        stroke: 0.4pt,
        inset: (x: 6pt, y: 4pt),
        [$e == #kw("true")$], [$"IsTrue"(id_r) implies "IsTrue"(id)$, $not "IsTrue"(id_r) implies not "IsTrue"(id)$],
        [$e != #kw("true")$], [$not "IsTrue"(id_r) implies "IsTrue"(id)$, $"IsTrue"(id_r) implies not "IsTrue"(id)$],
        [$e == #kw("false")$], [$not "IsTrue"(id_r) implies "IsTrue"(id)$, $"IsTrue"(id_r) implies not "IsTrue"(id)$],
        [$e != #kw("false")$], [$"IsTrue"(id_r) implies "IsTrue"(id)$, $not "IsTrue"(id_r) implies not "IsTrue"(id)$],
    )
]

The rules are symmetric with respect to operand order: #kw("true")
$==$ $e$ emits the same propositions as $e$ $==$ #kw("true"), and
likewise for the other three cases. When both operands are boolean
literals no propositions are emitted.

=== Conditional expressions

An expression #kw("if") $(e_c)$ $e_t$ #kw("else") $e_e$ with a
condition of origin $id_c$ types $e_t$ in an environment extended with
$cal(P) union.plus { "IsTrue"(id_c) }$ and $e_e$ in an environment
extended with $cal(P) union.plus { not "IsTrue"(id_c) }$. Propositions
emitted during the checking of either branch are wrapped in an
implication

$ "IsTrue"(id_c) implies p quad "(then branch)" $
$ not "IsTrue"(id_c) implies p quad "(else branch)" $

and re-emitted at the level of the conditional as a whole, so that the
propositions remain available to any surrounding context that later
proves or disproves the condition.

=== Logical `&&` and `||`

Short-circuit Boolean operators scope propositions over their
right-hand operands:

- For $e_1 #h(0.2em) #raw("&&") #h(0.2em) e_2$: $e_2$ is typed under
  $cal(P) union.plus { "IsTrue"(id_1) }$; propositions emitted during
  the checking of $e_2$ are wrapped in $"IsTrue"(id_1) implies dot$.
  The result of type origin $id_r$ emits
  $"IsTrue"(id_r) implies "IsTrue"(id_1)$ and
  $"IsTrue"(id_r) implies "IsTrue"(id_2)$.
- For $e_1 #h(0.2em) #raw("||") #h(0.2em) e_2$: dually, $e_2$ is typed
  under $cal(P) union.plus { not "IsTrue"(id_1) }$.

These rules make the proposition system agree with the short-circuit
evaluation semantics: any refinement that would be valid downstream of
a test holds immediately when the test has been passed.

=== Optional chaining

An expression $e ?. x$ where $e : {dots, x colon B, dots} ?$ has the
origin-level side effects

$ "RefinesTo"(id_"result", B) implies "RefinesTo"(id_e, {dots, x colon B, dots}) $

and, if the field is itself optional,

$ "RefinesTo"(id_"result", B) implies "RefinesTo"(id_x, B) . $

These track the fact that observation of a non-`nil` result proves
that the source was non-`nil`.

== Soundness

The following soundness theorem justifies the use of refinement in
place of structural subtyping.

#definition("Propositional soundness")[
    A typing derivation $Gamma ts e : A$ in the refinement-aware system
    is _sound_ when the non-refined judgment $Gamma ts e : A'$ is
    derivable in the structural system for some $A'$ with
    $A subtype A'$.
]

The soundness theorem, which we state without proof, guarantees that
every well-typed program in the refinement-aware system is also
well-typed in the structural fragment of Chapter 5, with possibly less
sharp types. Informally: refinement can only make types _better_, not
worse; removing the propositional engine from an implementation
yields a correct but less precise type system.
